### PR TITLE
Expose routingMode as query parameter

### LINKED ISSUE #31: v6: pagination not working due to realtime routing
Pagination doesn't seem to be working with API v6.

For example https://v6.db.transport.rest/journeys?from=8096021&to=8000085&departure=2023-08-01 returns 3 results with the latest departure at 04:46.

Still both `earlierRef` and `laterRef` are `null` so it's not possible to do follow-up request for the next results.

API v5 https://v5.db.transport.rest/journeys?from=8096021&to=8000085&departure=2023-08-01 returns working earlierRef and laterRef.

### PR DESCRIPTION
**Pull request by JohannesGandhi**
Contains the changes suggested in https://github.com/derhuerst/db-rest/issues/31#issuecomment-1662040711.

Fixes #31 
related: #42 

I didn't bump up the version number.

### CODE REVIEW

File: build/api-docs.js [hunk 1]
```diff
@@ -68,7 +68,16 @@ Uses [\`hafasClient.journeys()\`](https://github.com/public-transport/hafas-clie
...
+*Pagination isn't fully functioning with the default [\`routingMode\`](#routing-mode).*
+
 Check the [\`hafasClient.journeys()\` docs](https://github.com/public-transport/hafas-client/blob/6/docs/journeys.md) for more details.
+
+### Routing mode
+
+The \`routingMode\` parameter influences which data the system uses to compute the query results. The default is \`REALTIME\` and does *not* include canceled journeys. If you want canceled journeys to be included in the response, use \`HYBRID\` instead.
+Furthermore, \`REALTIME\` doesn't support [Pagination](#pagination) fully. If you need fully functioning pagination, use \`HYBRID\` instead.
+
+For more details on the different routing modes, see [here](https://github.com/public-transport/hafas-client/blob/45610fc951bb834e1b6f09e363ee820c0b92b673/p/db/readme.md#using-the-routingmode-option).
```
Comment (derhuerst) [inline build/api-docs.js]: Let's use (more) [meaningful links](https://www.smashingmagazine.com/2021/12/designing-better-links-websites-emails-guideline/#meaningful-links).

```suggestion
The `hafas-client` repository has [more details on the different routing modes](https://github.com/public-transport/hafas-client/blob/45610fc951bb834e1b6f09e363ee820c0b92b673/p/db/readme.md#using-the-routingmode-option).
```

**Comment by derhuerst** [comment]
Your PR looks very good, I have just one minor request.

Sorry it took me so long to look into this.

File: build/api-docs.js [hunk 2]
```diff
@@ -68,7 +68,16 @@ Uses [\`hafasClient.journeys()\`](https://github.com/public-transport/hafas-clie
...
 Given a response, you can also fetch more journeys matching the same criteria. Instead of \`from*\`, \`to*\` & \`departure\`/\`arrival\`, pass \`earlierRef\` from the first response as \`earlierThan\` to get journeys "before", or \`laterRef\` as \`laterThan\` to get journeys "after".
 
+*Pagination isn't fully functioning with the default [\`routingMode\`](#routing-mode).*
+
 Check the [\`hafasClient.journeys()\` docs](https://github.com/public-transport/hafas-client/blob/6/docs/journeys.md) for more details.
+
+### Routing mode
+
+The \`routingMode\` parameter influences which data the system uses to compute the query results. The default is \`REALTIME\` and does *not* include canceled journeys. If you want canceled journeys to be included in the response, use \`HYBRID\` instead.
+Furthermore, \`REALTIME\` doesn't support [Pagination](#pagination) fully. If you need fully functioning pagination, use \`HYBRID\` instead.
```
Comment (derhuerst) [inline build/api-docs.js:79]: These docs are interpreted as GitHub Flavoured Markdown, which expects two line breaks in between paragraphs.

```suggestion

Furthermore, \`REALTIME\` doesn't support [Pagination](#pagination) fully. If you need fully functioning pagination, use \`HYBRID\` instead.
```
```suggestion
Furthermore, \`REALTIME\` doesn't support [Pagination](#pagination) fully. If you need fully functioning pagination, use \`HYBRID\` instead.
```

**Comment by JohannesGandhi** [comment]
Glad to hear that. And no worries!

I accepted your suggestions.

File: api.js [hunk 3]
```diff
@@ -67,6 +69,13 @@ const mapRouteParsers = (route, parsers) => {
 			defaultStr: '*adult*',
 			parse: parseInteger
 		},
+		routingMode: {
+			description: 'HAFAS routing mode, see [Routing Mode](#routing-mode)',
```
Comment (derhuerst) [inline api.js]: The link won't work in the OpenAPI spec, which is generated from this markup. What do you think about referring to the section without linking to it?

```suggestion
			description: 'HAFAS routing mode, see the "Routing Mode" section',
```

Comment (JohannesGandhi) [reply api.js]: Ah right. I think it's good enough, yeah 👍

**Review by derhuerst — APPROVED** [review]

File: build/api-docs.js [hunk 4]
```diff
@@ -68,7 +68,17 @@ Uses [\`hafasClient.journeys()\`](https://github.com/public-transport/hafas-clie
...
+
 Check the [\`hafasClient.journeys()\` docs](https://github.com/public-transport/hafas-client/blob/6/docs/journeys.md) for more details.
+
+### Routing mode
+
+The \`routingMode\` parameter influences which data the system uses to compute the query results. The default is \`REALTIME\` and does *not* include canceled journeys. If you want canceled journeys to be included in the response, use \`HYBRID\` instead.
+
+Furthermore, \`REALTIME\` doesn't support [Pagination](#pagination) fully. If you need fully functioning pagination, use \`HYBRID\` instead.
+
+The `hafas-client` repository has [more details on the different routing modes](https://github.com/public-transport/hafas-client/blob/45610fc951bb834e1b6f09e363ee820c0b92b673/p/db/readme.md#using-the-routingmode-option).
```
Comment (derhuerst) [inline build/api-docs.js]: Whoops, we need to escape the backticks here.

```suggestion
The \`hafas-client\` repository has [more details on the different routing modes](https://github.com/public-transport/hafas-client/blob/45610fc951bb834e1b6f09e363ee820c0b92b673/p/db/readme.md#using-the-routingmode-option).
```

**Review by derhuerst — CHANGES_REQUESTED** [review]
Sorry, my suggestion has introduced an error that prevents building the docs.

Please also rebase your branch with `6`, I have configured GitHub Actions to run for PRs, too.

**Comment by JohannesGandhi** [comment]
I rebased with `6` and fixed the failed checks. Can you please verify everything is good now?

**Review by derhuerst — APPROVED** [review]

**Comment by derhuerst** [comment]
Sorry that it took me so long to review this that now the DB HAFAS API is shut off. 😢 – Thank you nevertheless!
